version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"
    volumes:
      - namenode:/hadoop/dfs/name
  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    env_file:
      - ./hadoop.env
    volumes:
      - datanode1:/hadoop/dfs/data
volumes:
  namenode:
  datanode1:
